# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: astro.flyfish@gmail.com
author_name: Weixiang Yu
create_example_module: false
custom_install: custom
enforce_style:
- ruff_lint
- black
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: eztaox
project_description: EzTaoX is a flexible framework for multi-wavelength and multi-survey
    AGN light-curve modeling using Gaussian Processes (GPs). Built on top of tinygp.
project_license: MIT
project_name: eztaox
project_organization: LSST-AGN-Variability
python_versions:
- '3.10'
- '3.11'
- '3.12'
test_lowest_version: direct
